image:
  repository: "<ECR_REPO_URL>/senthil-studio-chatbot-pgvector"
  tag: "16"

environment: prod

persistence:
  size: 20Gi

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 2Gi
