apiVersion: v1
kind: Secret
metadata:
  name: {{ include "studio-chatbot.name" . }}-secrets
  labels:
    {{- include "studio-chatbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.googleServiceAccountKey }}
  credentials.json: {{ .Values.secrets.googleServiceAccountKey | quote }}
  {{- end }}
  {{- if .Values.secrets.langchainApiKey }}
  LANGCHAIN_API_KEY: {{ .Values.secrets.langchainApiKey | quote }}
  {{- end }}
