apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "studio-chatbot.name" . }}-config
  labels:
    {{- include "studio-chatbot.labels" . | nindent 4 }}
data:
  APP_PROFILE: {{ .Values.config.appProfile | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  FAQ_S3_BUCKET: {{ .Values.config.faqS3Bucket | quote }}
  FAQ_S3_KEY: {{ .Values.config.faqS3Key | quote }}
  {{- if .Values.config.chatModelName }}
  CHAT_MODEL_NAME: {{ .Values.config.chatModelName | quote }}
  {{- end }}
  {{- if .Values.config.awsRegion }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  {{- end }}
  {{- if .Values.config.dbSecretName }}
  DB_SECRET_NAME: {{ .Values.config.dbSecretName | quote }}
  {{- end }}
  {{- if .Values.config.bedrockChatModelId }}
  BEDROCK_CHAT_MODEL_ID: {{ .Values.config.bedrockChatModelId | quote }}
  {{- end }}
